# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segmentation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='segmentation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12segmentation.proto\"*\n\x05Image\x12\x10\n\x08mimetype\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"1\n\x07Request\x12\x13\n\x03img\x18\x01 \x01(\x0b\x32\x06.Image\x12\x11\n\tvisualise\x18\x02 \x01(\x08\">\n\x10RegionOfInterest\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\t\n\x01w\x18\x03 \x01(\r\x12\t\n\x01h\x18\x04 \x01(\r\"\x9e\x01\n\x06Result\x12 \n\x10segmentation_img\x18\x01 \x03(\x0b\x32\x06.Image\x12\x1f\n\x04rois\x18\x02 \x03(\x0b\x32\x11.RegionOfInterest\x12\x0e\n\x06scores\x18\x03 \x03(\x02\x12\x11\n\tclass_ids\x18\x04 \x03(\r\x12\x13\n\x0b\x63lass_names\x18\x05 \x03(\t\x12\x19\n\tdebug_img\x18\x07 \x01(\x0b\x32\x06.Image\"\r\n\x0bMetaRequest\"#\n\nMetaResult\x12\x15\n\rknown_classes\x18\x01 \x01(\t2[\n\x14SemanticSegmentation\x12\x1e\n\x07segment\x12\x08.Request\x1a\x07.Result\"\x00\x12#\n\x04meta\x12\x0c.MetaRequest\x1a\x0b.MetaResult\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mimetype', full_name='Image.mimetype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='Image.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=64,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='Request.img', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visualise', full_name='Request.visualise', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=115,
)


_REGIONOFINTEREST = _descriptor.Descriptor(
  name='RegionOfInterest',
  full_name='RegionOfInterest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RegionOfInterest.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RegionOfInterest.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='RegionOfInterest.w', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='RegionOfInterest.h', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=179,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segmentation_img', full_name='Result.segmentation_img', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rois', full_name='Result.rois', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='Result.scores', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_ids', full_name='Result.class_ids', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_names', full_name='Result.class_names', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debug_img', full_name='Result.debug_img', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=340,
)


_METAREQUEST = _descriptor.Descriptor(
  name='MetaRequest',
  full_name='MetaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=355,
)


_METARESULT = _descriptor.Descriptor(
  name='MetaResult',
  full_name='MetaResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='known_classes', full_name='MetaResult.known_classes', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=392,
)

_REQUEST.fields_by_name['img'].message_type = _IMAGE
_RESULT.fields_by_name['segmentation_img'].message_type = _IMAGE
_RESULT.fields_by_name['rois'].message_type = _REGIONOFINTEREST
_RESULT.fields_by_name['debug_img'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['RegionOfInterest'] = _REGIONOFINTEREST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['MetaRequest'] = _METAREQUEST
DESCRIPTOR.message_types_by_name['MetaResult'] = _METARESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'segmentation_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'segmentation_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

RegionOfInterest = _reflection.GeneratedProtocolMessageType('RegionOfInterest', (_message.Message,), dict(
  DESCRIPTOR = _REGIONOFINTEREST,
  __module__ = 'segmentation_pb2'
  # @@protoc_insertion_point(class_scope:RegionOfInterest)
  ))
_sym_db.RegisterMessage(RegionOfInterest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'segmentation_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)

MetaRequest = _reflection.GeneratedProtocolMessageType('MetaRequest', (_message.Message,), dict(
  DESCRIPTOR = _METAREQUEST,
  __module__ = 'segmentation_pb2'
  # @@protoc_insertion_point(class_scope:MetaRequest)
  ))
_sym_db.RegisterMessage(MetaRequest)

MetaResult = _reflection.GeneratedProtocolMessageType('MetaResult', (_message.Message,), dict(
  DESCRIPTOR = _METARESULT,
  __module__ = 'segmentation_pb2'
  # @@protoc_insertion_point(class_scope:MetaResult)
  ))
_sym_db.RegisterMessage(MetaResult)



_SEMANTICSEGMENTATION = _descriptor.ServiceDescriptor(
  name='SemanticSegmentation',
  full_name='SemanticSegmentation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=394,
  serialized_end=485,
  methods=[
  _descriptor.MethodDescriptor(
    name='segment',
    full_name='SemanticSegmentation.segment',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='meta',
    full_name='SemanticSegmentation.meta',
    index=1,
    containing_service=None,
    input_type=_METAREQUEST,
    output_type=_METARESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEMANTICSEGMENTATION)

DESCRIPTOR.services_by_name['SemanticSegmentation'] = _SEMANTICSEGMENTATION

# @@protoc_insertion_point(module_scope)
