# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import segmentation_pb2 as segmentation__pb2


class SemanticSegmentationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.segment = channel.unary_unary(
        '/SemanticSegmentation/segment',
        request_serializer=segmentation__pb2.Request.SerializeToString,
        response_deserializer=segmentation__pb2.Result.FromString,
        )
    self.meta = channel.unary_unary(
        '/SemanticSegmentation/meta',
        request_serializer=segmentation__pb2.MetaRequest.SerializeToString,
        response_deserializer=segmentation__pb2.MetaResult.FromString,
        )


class SemanticSegmentationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def segment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def meta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SemanticSegmentationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'segment': grpc.unary_unary_rpc_method_handler(
          servicer.segment,
          request_deserializer=segmentation__pb2.Request.FromString,
          response_serializer=segmentation__pb2.Result.SerializeToString,
      ),
      'meta': grpc.unary_unary_rpc_method_handler(
          servicer.meta,
          request_deserializer=segmentation__pb2.MetaRequest.FromString,
          response_serializer=segmentation__pb2.MetaResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SemanticSegmentation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
